---------------------------------------------------------------------------
-- Generated by DB/Direct
---------------------------------------------------------------------------
module Database where

import Database.HaskellDB.DBLayout

import qualified Database.User_table
import qualified Database.Auth_table
import qualified Database.User_auth_table

website :: DBInfo
website = DBInfo {dbname = "website",
                  opts = DBOptions {useBString = False},
                  tbls = [TInfo {tname = "user_table",
                                 cols = [CInfo {cname = "user_name",
                                                descr = (StringT, False)},
                                         CInfo {cname = "password",
                                                descr = (StringT, False)},
                                         CInfo {cname = "enabled",
                                                descr = (BoolT, False)}]},
                          TInfo {tname = "auth_table",
                                 cols = [CInfo {cname = "auth_name",
                                                descr = (StringT, False)}]},
                          TInfo {tname = "user_auth_table",
                                 cols = [CInfo {cname = "user_name",
                                                descr = (StringT, False)},
                                         CInfo {cname = "auth_name",
                                                descr = (StringT, False)}]}]}